name: Fetch latest data

on:
  push:
  repository_dispatch:
  schedule:
    - cron:  '25 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://health-infobase.canada.ca/src/data/covidLive/covid19.csv > covid19__latest.csv
        curl https://health-infobase.canada.ca/src/data/covidLive/covid19-epiSummary-casesovertime.csv > covid19-epiSummary-casesovertime__latest.csv
        curl https://health-infobase.canada.ca/src/data/covidLive/covid19-epiSummary-agegroups2.csv > covid19-epiSummary-agegroups2__latest.csv
        curl https://health-infobase.canada.ca/src/data/covidLive/covid19-epiSummary-probableexposure.csv > covid19-epiSummary-probableexposure__latest.csv
        curl https://health-infobase.canada.ca/src/data/covidLive/covid19-epiSummary-symptoms.csv > covid19-epiSummary-symptoms__latest.csv
        curl https://health-infobase.canada.ca/src/data/covidLive/covid19-epiSummary-severity.csv > covid19-epiSummary-severity__latest.csv
    - name: Fetch table 13-10-0766-01
      run: |-
        curl https://www150.statcan.gc.ca/n1/tbl/csv/13100766-eng.zip -O
        unzip 13100766-eng.zip
        mv 13100766.csv 13100766__latest.csv
        mv 13100766_MetaData.csv 13100766_MetaData.csv__latest.csv
        rm 13100766-eng.zip
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
